on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
permissions:
  contents: write
  pull-requests: write
name: All actions
jobs:
  check-current-version:
    name: Check current version
    uses: >-
      NovoNordisk-OpenSource/r.workflows/.github/workflows/check_current_version.yaml@main
check-nn-version:
  name: R-CMD-check NN versions
  runs-on: '${{ matrix.os }}'
  strategy:
    fail-fast: false
    matrix:
      os:
        - macos-latest
        - windows-latest
        - ubuntu-latest
      config:
        - date: 2023-10-25
          r: 4.3.1
        - date: 2024-08-06
          r: 4.4.1
  env:
    R_KEEP_PKG_SOURCE: 'yes'
  steps:
    - uses: actions/checkout@v4
    - name: Package specific setup
      if: ${{ inputs.use_local_setup_action }}
      uses: ./.github/actions/setup
    - uses: r-lib/actions/setup-pandoc@v2
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '${{ matrix.config.r }}'
        use-public-rspm: false
    - name: Install curl
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt install libcurl4-openssl-dev
    - name: Configure package repos
      run: >
        options(
          repos = c(CRAN = "https://packagemanager.posit.co/cran/${{matrix.config.date}}")
          )
      shell: 'Rscript {0}'
    - uses: r-lib/actions/setup-r-dependencies@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: 'any::rcmdcheck'
        needs: check
    - uses: r-lib/actions/check-r-package@v2
      with:
        upload-snapshots: true
  pkgdown:
    name: Pkgdown site
    uses: NovoNordisk-OpenSource/r.workflows/.github/workflows/pkgdown.yaml@main
  coverage:
    name: Coverage report
    uses: NovoNordisk-OpenSource/r.workflows/.github/workflows/coverage.yaml@main
    #secrets: inherit # Required if use_codecov below is true, in order to access organisational codecov token
    with:
      use_codecov: false # Change to true if you want to upload coverage results to codecov.io.
  megalinter:
    name: Megalinter
    uses: NovoNordisk-OpenSource/r.workflows/.github/workflows/megalinter.yaml@main
